env:
  - CGO_ENABLED=0
  - PROJECT=github.com/realvnc-labs/tacoscript
builds:
  - id: tacoscript
    main: ./
    binary: tacoscript
    ldflags:
      - -X '{{.Env.PROJECT}}/cmd.Version={{.Version}}'
      - -X '{{.Env.PROJECT}}/cmd.BuildTime={{.Date}}'
      - -X '{{.Env.PROJECT}}/cmd.GitCommit={{.Commit}}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    gomips:
      - hardfloat
      - softfloat
    ignore:
      # TODO: remove when https://github.com/go-ole/go-ole/issues/202 will be fixed
      - goos: windows
        goarch: arm

archives:
  - id: all
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      tacoscript_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
release:
  github:
    owner: realvnc-labs
    name: tacoscript
  draft: true
