name: Test Linux
on: [push]
jobs:
  sca:
    name: Sca
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.50.1
          args: -c .golangci.yml

  test:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Test Linux
        run: go test -race ./...